spring:
  profiles:
    active: dev
  application:
    name: url-shortener

app:
  short-code:
    length: 7
    max-retries: 5
  base-url: http://localhost:8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
